name: Lint

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  typecheck:
    name: "3.12"
    runs-on: ubuntu-latest

    steps:
      - name: Set up the code base
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install flake8
        run: pip install flake8

      - name: Run mypy
        run: python -m flake8 .
