name: Test

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  test:
    name: ${{ matrix.python_version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python_version: [ "3.8", "3.9", "3.10", "3.11", "3.12" ]

    steps:
      - name: Set up the code base
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python_version }}"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the test suite
        run: python -m pytest -vv tests.py
