name: Test with pytest and hypothesis

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Set up the code base
    - uses: actions/checkout@v4
    
    - name: Set up Python and run test suite
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "pip"
    - run: |
        pip install -r requirements.txt
        python -m pytest tests.py
