name: Typecheck with mypy

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  typecheck:
    name: ${{ matrix.python_version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python_version: [ "3.8", "3.9", "3.10", "3.11", "3.12" ]

    steps:
      - name: Set up the code base
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python_version }}"
          cache: "pip"

      - name: Install mypy
        run: pip install mypy

      - name: Run mypy
        run: python -m mypy --strict --disallow-any-explicit --pretty --show-error-context .
